databases:
  - name: vajra-db
    databaseName: vajra
    user: vajra_user
    plan: free

services:
  - type: web
    name: vajra-points
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vajra-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
